### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by glarence** [sharish/CreditCardView#14] opened 2016-10-23 17:32 UTC
Hi sharish, I'm getting a null object reference error when trying to edit an existing credit card. It appears in your CardExpiryFragment in the focus method when the cardExpiryView calls selectAll().
![screen shot 2016-10-23 at 10 31 46 am](https://cloud.githubusercontent.com/assets/8648994/19628140/f50c34ce-990b-11e6-8106-c51885315275.png)

**Comment by sharish** [comment] 2016-10-28 03:47
Duplicate of #10

**Closed by sharish** 2016-10-28 03:47 UTC
